language: node_js
notifications:
  email: false
  slack:
    rooms:
      secure: K4gEBdaBT6W69jk0+kGCP2fCn+IgtgYmADlJBmN0uxeQ9vbU2ubKjOJzZ7pCR06RvNCudyTsKYLDOu1sgpJhrU3l9+ELiuXRaHXspNHmvDJXbU704eHrL6ahAlr7OLDokaeWXz7c78znvvOwPVKxdfKuYTUQdFKbtr6ZnMlVMC+iagBiPdcWbuL2/HVuxoVAz6+KiT+eh5/Rj++GlxBIVNJtf/L9jHYJ9ZwrEsILeGNXR+b+qUgGST41Ft+aeLX6ORwbuSfki2qB1UUxrKSYtzUdP3xWZJ5GRFOM6t0Rb5kVn4MrFReHF5MWlXT85dj1dpq6UINzohhRkfjmhfeggBcbBK6uNVdKyrTkgnFltIbqP8pZN8kR3KUEik7GrmJXPSjh/hg41E3Kj2M4htIepB2QdHukGW+/4A5GaLvDWPOwoLByCn2KB0+pvutMkROWmgOmAD5V8+vC6n2pkpUnqBKNRDQ3lzEpkRsaRSU0Vp2t6v57dRVRJygDxAslH5TXoVj9fq3fQ797Y56mDNrWKZxOeBwMqbLiaYpgWofzHIa+3xfNbjmNZskBIN1+Fh3q0/MOro5pPTMtnJmqciieWpAzZwpG34JAD7WejQXtB+Wbe3jdQcYUyN8BAJBq7P7ejNbT0/PtgSm0xHGJM5KrlCCDHMH7Hhm53MJQUv97vPM=
